config/routes.rb
PoetryBlog::Application.routes.draw do
  resources :poems

end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :poems
end

app/models/poem.rb
class Poem < ActiveRecord::Base
  belongs_to :author

  def author_name
    self.author.name
  end

  validates :title, presence: true
  validates :content, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/poems_controller.rb
class PoemsController < ApplicationController
  before_action :set_poem, only: [:show, :edit, :update, :destroy]

  # GET /poems
  # GET /poems.json
  def index
    @poems = Poem.all
  end

  # GET /poems/1
  # GET /poems/1.json
  def show
  end

  # GET /poems/new
  def new
    @poem = Poem.new
  end

  # GET /poems/1/edit
  def edit
  end

  # POST /poems
  # POST /poems.json
  def create
    @poem = Poem.new(poem_params)

    respond_to do |format|
      if @poem.save
        format.html { redirect_to @poem, notice: 'Poem was successfully created.' }
        format.json { render action: 'show', status: :created, location: @poem }
      else
        format.html { render action: 'new' }
        format.json { render json: @poem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /poems/1
  # PATCH/PUT /poems/1.json
  def update
    respond_to do |format|
      if @poem.update(poem_params)
        format.html { redirect_to @poem, notice: 'Poem was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @poem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /poems/1
  # DELETE /poems/1.json
  def destroy
    @poem.destroy
    respond_to do |format|
      format.html { redirect_to poems_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poem
      @poem = Poem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poem_params
      params.require(:poem).permit(:title, :content, :author_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/poems_helper.rb
module PoemsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PoetryBlog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/poems/_form.html.erb
<%= form_for(@poem) do |f| %>
  <% if @poem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@poem.errors.count, "error") %> prohibited this poem from being saved:</h2>

      <ul>
      <% @poem.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, required: true %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content, required: true %>
  </div>
  <div class="field">
    <%= f.label :author_id %><br>
    <%= f.number_field :author_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/poems/edit.html.erb
<h1>Editing poem</h1>

<%= render 'form' %>

<%= link_to 'Show', @poem %> |
<%= link_to 'Back', poems_path %>

app/views/poems/index.html.erb
<h1>Listing poems</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Author</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @poems.each do |poem| %>
      <tr>
        <td><%= poem.title %></td>
        <td><%= poem.content %></td>
        <td><%= poem.author_id %></td>
        <td><%= link_to 'Show', poem %></td>
        <td><%= link_to 'Edit', edit_poem_path(poem) %></td>
        <td><%= link_to 'Destroy', poem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Poem', new_poem_path %>

app/views/poems/new.html.erb
<h1>New poem</h1>

<%= render 'form' %>

<%= link_to 'Back', poems_path %>

app/views/poems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @poem.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @poem.content %>
</p>

<p>
  <strong>Author:</strong>
  <%= @poem.author_id %>
</p>

<%= link_to 'Edit', edit_poem_path(@poem) %> |
<%= link_to 'Back', poems_path %>